---
- name: Render container environment file
  template:
    src: container.env.j2
    dest: /home/{{ container_user }}/mongodb/container.env
    owner: "{{ container_user }}"
    group: "{{ container_user }}"
    mode: '0640'

