---
- name: Setup Podman and MongoDB containers (dev)
  hosts: db_primary:db_replicas     # union of both groups
  gather_facts: yes
  become: yes

  roles:
    - role: podman
    - role: mongodb

- name: Configure MongoDB replica set
  hosts: db_primary                 # run RS orchestration from the primary
  gather_facts: no
  become: yes

  roles:
    - role: replication

